/*
 * Velocity, a modification for Discord's desktop app
 * Copyright (c) 2025 RoScripter999 and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

import type * as t from "@velocity-types";
import { findByCodeLazy, findByPropsLazy } from "@webpack";

import { waitForStore } from "./internal";

export const Flux: t.Flux = findByPropsLazy("connectStores");

export type GenericStore = t.FluxStore & Record<string, any>;

export const DraftType = findByPropsLazy("ChannelMessage", "SlashCommand");

export let MessageStore: t.MessageStore;

export let AccessibilityStore: t.AccessibilityStore;
export let ActiveChannelsStore: t.ActiveChannelsStore;
export let ActiveJoinedThreadsStore: t.ActiveJoinedThreadsStore;
export let ActiveThreadsStore: t.ActiveThreadsStore;
export let ActivityInviteEducationStore: t.ActivityInviteEducationStore;
export let ActivityInviteModalStore: t.ActivityInviteModalStore;
export let ActivityLauncherStore: t.ActivityLauncherStore;
export let ActivityShelfStore: t.ActivityShelfStore;
export let ActivityTrackingStore: t.ActivityTrackingStore;
export let AdyenStore: t.AdyenStore;
export let AgeVerificationStore: t.AgeVerificationStore;
export let AnalyticsLogStore: t.AnalyticsLogStore;
export let ApexExperimentStore: t.ApexExperimentStore;
export let AppIconPersistedStoreState: t.AppIconPersistedStoreState;
export let AppLauncherLastUsedCommandStore: t.AppLauncherLastUsedCommandStore;
export let AppLauncherStore: t.AppLauncherStore;
export let ApplicationAssetsStore: t.ApplicationAssetsStore;
export let ApplicationBuildStore: t.ApplicationBuildStore;
export let ApplicationCommandAutocompleteStore: t.ApplicationCommandAutocompleteStore;
export let ApplicationCommandFrecencyStore: t.ApplicationCommandFrecencyStore;
export let ApplicationCommandIndexStore: t.ApplicationCommandIndexStore;
export let ApplicationCommandStore: t.ApplicationCommandStore;
export let ApplicationDirectoryApplicationsStore: t.ApplicationDirectoryApplicationsStore;
export let ApplicationDirectoryCategoriesStore: t.ApplicationDirectoryCategoriesStore;
export let ApplicationDirectorySearchStore: t.ApplicationDirectorySearchStore;
export let ApplicationDirectorySimilarApplicationsStore: t.ApplicationDirectorySimilarApplicationsStore;
export let ApplicationStore: t.ApplicationStore;
export let ApplicationStoreDirectoryStore: t.ApplicationStoreDirectoryStore;
export let ApplicationStoreLocationStore: t.ApplicationStoreLocationStore;
export let ApplicationStoreUserSettingsStore: t.ApplicationStoreUserSettingsStore;
export let ApplicationStreamingSettingsStore: t.ApplicationStreamingSettingsStore;
export let ApplicationStreamingStore: t.ApplicationStreamingStore;
export let ApplicationStreamPreviewStore: t.ApplicationStreamPreviewStore;
export let ApplicationSubscriptionChannelNoticeStore: t.ApplicationSubscriptionChannelNoticeStore;
export let ApplicationSubscriptionStore: t.ApplicationSubscriptionStore;
export let ApplicationViewStore: t.ApplicationViewStore;
export let AppliedGuildBoostStore: t.AppliedGuildBoostStore;
export let AppViewStore: t.AppViewStore;
export let ArchivedThreadsStore: t.ArchivedThreadsStore;
export let AuthenticationStore: t.AuthenticationStore;
export let AuthInviteStore: t.AuthInviteStore;
export let AuthorizedAppsStore: t.AuthorizedAppsStore;
export let AuthSessionsStore: t.AuthSessionsStore;
export let AutoUpdateStore: t.AutoUpdateStore;
export let AVErrorStore: t.AVErrorStore;
export let BasicGuildStore: t.BasicGuildStore;
export let BillingInfoStore: t.BillingInfoStore;
export let BitRateStore: t.BitRateStore;
export let BraintreeStore: t.BraintreeStore;
export let BrowserCheckoutStateStore: t.BrowserCheckoutStateStore;
export let BrowserHandoffStore: t.BrowserHandoffStore;
export let BuildOverrideStore: t.BuildOverrideStore;
export let BurstReactionEffectsStore: t.BurstReactionEffectsStore;
export let CacheStore: t.CacheStore;
export let CallChatToastsStore: t.CallChatToastsStore;
export let CallStore: t.CallStore;
export let CategoryCollapseStore: t.CategoryCollapseStore;
export let CertifiedDeviceStore: t.CertifiedDeviceStore;
export let ChangelogStore: t.ChangelogStore;
export let ChannelFollowerStatsStore: t.ChannelFollowerStatsStore;
export let ChannelFollowingPublishBumpStore: t.ChannelFollowingPublishBumpStore;
export let ChannelListStore: t.ChannelListStore;
export let ChannelListUnreadsStore: t.ChannelListUnreadsStore;
export let ChannelListVoiceCategoryStore: t.ChannelListVoiceCategoryStore;
export let ChannelMemberCountStore: t.ChannelMemberCountStore;
export let ChannelMemberStore: t.ChannelMemberStore;
export let ChannelPinsStore: t.ChannelPinsStore;
export let ChannelRTCStore: t.ChannelRTCStore;
export let ChannelSectionStore: t.ChannelSectionStore;
export let ChannelSettingsStore: t.ChannelSettingsStore;
export let ChannelStore: t.ChannelStore;
export let ChannelSKUStore: t.ChannelSKUStore;
export let ClientThemesBackgroundStore: t.ClientThemesBackgroundStore;
export let ClipsStore: t.ClipsStore;
export let CollapsedVoiceChannelStore: t.CollapsedVoiceChannelStore;
export let CollectiblesMarketingsStore: t.CollectiblesMarketingsStore;
export let CollectiblesShopHomesStore: t.CollectiblesShopHomesStore;
export let ConnectedAccountsStore: t.ConnectedAccountsStore;
export let ConnectedAppsStore: t.ConnectedAppsStore;
export let ConsentStore: t.ConsentStore;
export let ContentInventoryActivityStore: t.ContentInventoryActivityStore;
export let ContextMenuStore: t.ContextMenuStore;
export let DCFEventStore: t.DCFEventStore;
export let DefaultRouteStore: t.DefaultRouteStore;
export let DetectedOffPlatformPremiumPerksStore: t.DetectedOffPlatformPremiumPerksStore;
export let DeveloperActivityShelfStore: t.DeveloperActivityShelfStore;
export let DeveloperExperimentStore: t.DeveloperExperimentStore;
export let DeveloperOptionsStore: t.DeveloperOptionsStore;
export let DeviceFrecencyStore: t.DeviceFrecencyStore;
export let DevToolsSettingsStore: t.DevToolsSettingsStore;
export let DevToolsDevSettingsStore: t.DevToolsDevSettingsStore;
export let DevToolsDesignTogglesStore: t.DevToolsDesignTogglesStore;
export let DimensionStore: t.DimensionStore;
export let DismissibleContentFrameworkStore: t.DismissibleContentFrameworkStore;
export let DismissibleContentShownStateStore: t.DismissibleContentShownStateStore;
export let DispatchApplicationLaunchSetupStore: t.DispatchApplicationLaunchSetupStore;
export let DispatchApplicationStore: t.DispatchApplicationStore;
export let DispatchManagerStore: t.DispatchManagerStore;
export let DraftStore: t.DraftStore;
export let EditMessageStore: t.EditMessageStore;
export let EmailSettingsStore: t.EmailSettingsStore;
export let EmbeddedActivitiesStore: t.EmbeddedActivitiesStore;
export let EmojiStore: t.EmojiStore;
export let EntitlementStore: t.EntitlementStore;
export let ExpandedGuildFolderStore: t.ExpandedGuildFolderStore;
export let ExperimentStore: t.ExperimentStore;
export let ExternalStreamingStore: t.ExternalStreamingStore;
export let FalsePositiveStore: t.FalsePositiveStore;
export let FavoritesSuggestionStore: t.FavoritesSuggestionStore;
export let FavoriteStore: t.FavoriteStore;
export let FirstPartyRichPresenceStore: t.FirstPartyRichPresenceStore;
export let ForumActivePostStore: t.ForumActivePostStore;
export let ForumPostMessagesStore: t.ForumPostMessagesStore;
export let ForumSearchStore: t.ForumSearchStore;
export let FrecencyStore: t.FrecencyStore;
export let FriendsStore: t.FriendsStore;
export let GatedChannelStore: t.GatedChannelStore;
export let GameConsoleStore: t.GameConsoleStore;
export let GameLibraryViewStore: t.GameLibraryViewStore;
export let GamePartyStore: t.GamePartyStore;
export let GameStore: t.GameStore;
export let GiftCodeStore: t.GiftCodeStore;
export let GuildAffinitiesStore: t.GuildAffinitiesStore;
export let GuildAvailabilityStore: t.GuildAvailabilityStore;
export let GuildBoostSlotStore: t.GuildBoostSlotStore;
export let GuildCategoryStore: t.GuildCategoryStore;
export let GuildChannelStore: t.GuildChannelStore;
export let GuildMemberCountStore: t.GuildMemberCountStore;
export let GuildMemberRequesterStore: t.GuildMemberRequesterStore;
export let GuildMemberStore: t.GuildMemberStore;
export let GuildNSFWAgreeStore: t.GuildNSFWAgreeStore;
export let GuildOnboardingHomeSettingsStore: t.GuildOnboardingHomeSettingsStore;
export let GuildOnboardingMemberActionStore: t.GuildOnboardingMemberActionStore;
export let GuildOnboardingStore: t.GuildOnboardingStore;
export let GuildReadStateStore: t.GuildReadStateStore;
export let GuildRoleStore: t.GuildRoleStore;
export let GuildRoleSubscriptionsStore: t.GuildRoleSubscriptionsStore;
export let GuildScheduledEventStore: t.GuildScheduledEventStore;
export let GuildSettingsStore: t.GuildSettingsStore;
export let GuildStickersStore: t.GuildStickersStore;
export let GuildStore: t.GuildStore;
export let GuildSubscriptionsStore: t.GuildSubscriptionsStore;
export let GuildTemplateStore: t.GuildTemplateStore;
export let GuildVerificationStore: t.GuildVerificationStore;
export let HookErrorStore: t.HookErrorStore;
export let IdleStore: t.IdleStore;
export let ImpersonateStore: t.ImpersonateStore;
export let IncomingCallStore: t.IncomingCallStore;
export let InstanceIdStore: t.InstanceIdStore;
export let InstantInviteStore: t.InstantInviteStore;
export let InstallationManagerStore: t.InstallationManagerStore;
export let IntegrationQueryStore: t.IntegrationQueryStore;
export let InteractionStore: t.InteractionStore;
export let InviteStore: t.InviteStore;
export let JoinedThreadsStore: t.JoinedThreadsStore;
export let LaunchableGameStore: t.LaunchableGameStore;
export let LayoutStore: t.LayoutStore;
export let LayerStore: t.LayerStore;
export let LibraryApplicationStatisticsStore: t.LibraryApplicationStatisticsStore;
export let LibraryApplicationStore: t.LibraryApplicationStore;
export let LocalActivityStore: t.LocalActivityStore;
export let LocaleStore: t.LocaleStore;
export let LoginRequiredActionStore: t.LoginRequiredActionStore;
export let LurkingStore: t.LurkingStore;
export let MaskedLinkStore: t.MaskedLinkStore;
export let MediaEngineStore: t.MediaEngineStore;
export let MessageReactionsStore: t.MessageReactionsStore;
export let MessageRequestStore: t.MessageRequestStore;
export let MFAStore: t.MFAStore;
export let MultiAccountStore: t.MultiAccountStore;
export let NetworkStore: t.NetworkStore;
export let NewUserStore: t.NewUserStore;
export let NonGameStore: t.NonGameStore;
export let NativePermissionStore: t.NativePermissionStore;
export let NotificationSettingsStore: t.NotificationSettingsStore;
export let NotificationCenterItemsStore: t.NotificationCenterItemsStore;
export let NoteStore: t.NoteStore;
export let OverlayRTCConnectionStore: t.OverlayRTCConnectionStore;
export let OverridePremiumTypeStore: t.OverridePremiumTypeStore;
export let PaymentSourceStore: t.PaymentSourceStore;
export let PermissionStore: t.PermissionStore;
export let PermissionSpeakStore: t.PermissionSpeakStore;
export let PermissionVADStore: t.PermissionVADStore;
export let PendingReplyStore: t.PendingReplyStore;
export let PhoneStore: t.PhoneStore;
export let PictureInPictureStore: t.PictureInPictureStore;
export let PoggermodeSettingsStore: t.PoggermodeSettingsStore;
export let PoggermodeStore: t.PoggermodeStore;
export let PopoutWindowStore: t.PopoutWindowStore;
export let PremiumPaymentModalStore: t.PremiumPaymentModalStore;
export let PresenceStore: t.PresenceStore;
export let PrivateChannelSortStore: t.PrivateChannelSortStore;
export let PromotionsStore: t.PromotionsStore;
export let QuickSwitcherStore: t.QuickSwitcherStore;
export let QuestStore: t.QuestStore;
export let RawGuildEmojiStore: t.RawGuildEmojiStore;
export let ReadStateStore: GenericStore;
export let ReferencedMessageStore: t.ReferencedMessageStore;
export let RegionStore: t.RegionStore;
export let RelationshipStore: t.RelationshipStore;
export let RTCConnectionDesyncStore: t.RTCConnectionDesyncStore;
export let RTCConnectionStore: t.RTCConnectionStore;
export let RTCDebugStore: t.RTCDebugStore;
export let RTCRegionStore: t.RTCRegionStore;
export let RunningGameStore: t.RunningGameStore;
export let SaveableChannelsStore: t.SaveableChannelsStore;
export let SearchMessageStore: t.SearchMessageStore;
export let SelectivelySyncedUserSettingsStore: t.SelectivelySyncedUserSettingsStore;
export let SecureFramesPersistedStore: t.SecureFramesPersistedStore;
export let SelectedChannelStore: t.SelectedChannelStore;
export let SelectedGuildStore: t.SelectedGuildStore;
export let SelfPresenceStore: t.SelfPresenceStore;
export let SessionsStore: t.SessionsStore;
export let SlowmodeStore: t.SlowmodeStore;
export let SortedGuildStore: t.SortedGuildStore;
export let SortedVoiceStateStore: t.SortedVoiceStateStore;
export let SoundboardStore: t.SoundboardStore;
export let SoundpackStore: t.SoundpackStore;
export let SpamMessageRequestStore: t.SpamMessageRequestStore;
export let SpeakingStore: t.SpeakingStore;
export let SpellcheckStore: t.SpellcheckStore;
export let SKUStore: t.SKUStore;
export let SpotifyProtocolStore: t.SpotifyProtocolStore;
export let SpotifyStore: t.SpotifyStore;
export let StageChannelParticipantStore: t.StageChannelParticipantStore;
export let StageChannelRoleStore: t.StageChannelRoleStore;
export let StageChannelSelfRichPresenceStore: t.StageChannelSelfRichPresenceStore;
export let StageInstanceStore: t.StageInstanceStore;
export let StickerMessagePreviewStore: t.StickerMessagePreviewStore;
export let StickersPackStore: t.StickersPackStore;
export let StickersPersistedStore: t.StickersPersistedStore;
export let StickersStore: t.StickersStore;
export let StreamerModeStore: t.StreamerModeStore;
export let SubscriptionPlanStore: t.SubscriptionPlanStore;
export let SubscriptionRoleStore: t.SubscriptionRoleStore;
export let SubscriptionStore: t.SubscriptionStore;
export let SystemAnalyticsStore: t.SystemAnalyticsStore;
export let TestModeStore: t.TestModeStore;
export let ThemeStore: t.ThemeStore;
export let ThreadMemberListStore: t.ThreadMemberListStore;
export let ThreadMembersStore: t.ThreadMembersStore;
export let ThreadMessageStore: t.ThreadMessageStore;
export let ThreadSummaryStore: t.ThreadSummaryStore;
export let TopEmojiStore: t.TopEmojiStore;
export let TypingStore: t.TypingStore;
export let UnsyncedUserSettingsStore: t.UnsyncedUserSettingsStore;
export let UploadAttachmentStore: t.UploadAttachmentStore;
export let UploadStore: t.UploadStore;
export let UserAffinitiesV2Store: t.UserAffinitiesV2Store;
export let UserGuildJoinRequestStore: t.UserGuildJoinRequestStore;
export let UserGuildSettingsStore: t.UserGuildSettingsStore;
export let UserOfferStore: t.UserOfferStore;
export let UserProfileStore: t.UserProfileStore;
export let UserRequiredActionStore: t.UserRequiredActionStore;
export let UserSettingsOverridesStore: t.UserSettingsOverridesStore;
export let UserSettingsProtoStore: t.UserSettingsProtoStore;
export let UserStore: t.UserStore;
export let VerifiedKeyStore: t.VerifiedKeyStore;
export let VideoBackgroundStore: t.VideoBackgroundStore;
export let VideoQualityModeStore: t.VideoQualityModeStore;
export let VideoStreamStore: t.VideoStreamStore;
export let VirtualCurrencyStore: t.VirtualCurrencyStore;
export let VoiceChannelEffectsPersistedStore: t.VoiceChannelEffectsPersistedStore;
export let VoiceStateStore: t.VoiceStateStore;
export let WindowStore: t.WindowStore;
export let WowMomentConfirmationStore: t.WowMomentConfirmationStore;

/**
 * @see jsdoc of {@link t.useStateFromStores}
 */
export const useStateFromStores: t.useStateFromStores = findByCodeLazy("useStateFromStores");

waitForStore("AccessibilityStore", s => {
    AccessibilityStore = s;
    Velocity.Api.Styles.initReducedMotionStyle(s);
});
waitForStore("ActiveChannelsStore", s => ActiveChannelsStore = s);
waitForStore("ActiveJoinedThreadsStore", s => ActiveJoinedThreadsStore = s);
waitForStore("ActiveThreadsStore", s => ActiveThreadsStore = s);
waitForStore("ActivityInviteEducationStore", s => ActivityInviteEducationStore = s);
waitForStore("ActivityInviteModalStore", s => ActivityInviteModalStore = s);
waitForStore("ActivityLauncherStore", s => ActivityLauncherStore = s);
waitForStore("ActivityShelfStore", s => ActivityShelfStore = s);
waitForStore("ActivityTrackingStore", s => ActivityTrackingStore = s);
waitForStore("AdyenStore", s => AdyenStore = s);
waitForStore("AgeVerificationStore", s => AgeVerificationStore = s);
waitForStore("AnalyticsLogStore", s => AnalyticsLogStore = s);
waitForStore("ApexExperimentStore", s => ApexExperimentStore = s);
waitForStore("AppIconPersistedStoreState", s => AppIconPersistedStoreState = s);
waitForStore("AppLauncherLastUsedCommandStore", s => AppLauncherLastUsedCommandStore = s);
waitForStore("AppLauncherStore", s => AppLauncherStore = s);
waitForStore("ApplicationAssetsStore", s => ApplicationAssetsStore = s);
waitForStore("ApplicationBuildStore", s => ApplicationBuildStore = s);
waitForStore("ApplicationCommandAutocompleteStore", s => ApplicationCommandAutocompleteStore = s);
waitForStore("ApplicationCommandFrecencyStore", s => ApplicationCommandFrecencyStore = s);
waitForStore("ApplicationCommandIndexStore", s => ApplicationCommandIndexStore = s);
waitForStore("ApplicationCommandStore", s => ApplicationCommandStore = s);
waitForStore("ApplicationDirectoryApplicationsStore", s => ApplicationDirectoryApplicationsStore = s);
waitForStore("ApplicationDirectoryCategoriesStore", s => ApplicationDirectoryCategoriesStore = s);
waitForStore("ApplicationDirectorySearchStore", s => ApplicationDirectorySearchStore = s);
waitForStore("ApplicationDirectorySimilarApplicationsStore", s => ApplicationDirectorySimilarApplicationsStore = s);
waitForStore("ApplicationStore", s => ApplicationStore = s);
waitForStore("ApplicationStoreDirectoryStore", s => ApplicationStoreDirectoryStore = s);
waitForStore("ApplicationStoreLocationStore", s => ApplicationStoreLocationStore = s);
waitForStore("ApplicationStoreUserSettingsStore", s => ApplicationStoreUserSettingsStore = s);
waitForStore("ApplicationStreamingSettingsStore", s => ApplicationStreamingSettingsStore = s);
waitForStore("ApplicationStreamingStore", s => ApplicationStreamingStore = s);
waitForStore("ApplicationStreamPreviewStore", s => ApplicationStreamPreviewStore = s);
waitForStore("ApplicationSubscriptionChannelNoticeStore", s => ApplicationSubscriptionChannelNoticeStore = s);
waitForStore("ApplicationSubscriptionStore", s => ApplicationSubscriptionStore = s);
waitForStore("ApplicationViewStore", s => ApplicationViewStore = s);
waitForStore("AppliedGuildBoostStore", s => AppliedGuildBoostStore = s);
waitForStore("AppViewStore", s => AppViewStore = s);
waitForStore("ArchivedThreadsStore", s => ArchivedThreadsStore = s);
waitForStore("AuthenticationStore", s => AuthenticationStore = s);
waitForStore("AuthInviteStore", s => AuthInviteStore = s);
waitForStore("AuthorizedAppsStore", s => AuthorizedAppsStore = s);
waitForStore("AuthSessionsStore", s => AuthSessionsStore = s);
waitForStore("AutoUpdateStore", s => AutoUpdateStore = s);
waitForStore("AVErrorStore", s => AVErrorStore = s);
waitForStore("BasicGuildStore", s => BasicGuildStore = s);
waitForStore("BillingInfoStore", s => BillingInfoStore = s);
waitForStore("BitRateStore", s => BitRateStore = s);
waitForStore("BraintreeStore", s => BraintreeStore = s);
waitForStore("BrowserCheckoutStateStore", s => BrowserCheckoutStateStore = s);
waitForStore("BrowserHandoffStore", s => BrowserHandoffStore = s);
waitForStore("BuildOverrideStore", s => BuildOverrideStore = s);
waitForStore("BurstReactionEffectsStore", s => BurstReactionEffectsStore = s);
waitForStore("CacheStore", s => CacheStore = s);
waitForStore("CallChatToastsStore", s => CallChatToastsStore = s);
waitForStore("CallStore", s => CallStore = s);
waitForStore("CategoryCollapseStore", s => CategoryCollapseStore = s);
waitForStore("CertifiedDeviceStore", s => CertifiedDeviceStore = s);
waitForStore("ChangelogStore", s => ChangelogStore = s);
waitForStore("ChannelFollowerStatsStore", s => ChannelFollowerStatsStore = s);
waitForStore("ChannelFollowingPublishBumpStore", s => ChannelFollowingPublishBumpStore = s);
waitForStore("ChannelListStore", s => ChannelListStore = s);
waitForStore("ChannelListUnreadsStore", s => ChannelListUnreadsStore = s);
waitForStore("ChannelListVoiceCategoryStore", s => ChannelListVoiceCategoryStore = s);
waitForStore("ChannelMemberCountStore", s => ChannelMemberCountStore = s);
waitForStore("ChannelMemberStore", s => ChannelMemberStore = s);
waitForStore("ChannelPinsStore", s => ChannelPinsStore = s);
waitForStore("ChannelRTCStore", s => ChannelRTCStore = s);
waitForStore("ChannelSectionStore", s => ChannelSectionStore = s);
waitForStore("ChannelSettingsStore", s => ChannelSettingsStore = s);
waitForStore("ChannelStore", s => ChannelStore = s);
waitForStore("ChannelSKUStore", s => ChannelSKUStore = s);
waitForStore("ClientThemesBackgroundStore", s => ClientThemesBackgroundStore = s);
waitForStore("ClipsStore", s => ClipsStore = s);
waitForStore("CollapsedVoiceChannelStore", s => CollapsedVoiceChannelStore = s);
waitForStore("CollectiblesMarketingsStore", s => CollectiblesMarketingsStore = s);
waitForStore("CollectiblesShopHomesStore", s => CollectiblesShopHomesStore = s);
waitForStore("ConnectedAccountsStore", s => ConnectedAccountsStore = s);
waitForStore("ConnectedAppsStore", s => ConnectedAppsStore = s);
waitForStore("ConsentStore", s => ConsentStore = s);
waitForStore("ContentInventoryActivityStore", s => ContentInventoryActivityStore = s);
waitForStore("ContextMenuStore", s => ContextMenuStore = s);
waitForStore("DCFEventStore", s => DCFEventStore = s);
waitForStore("DefaultRouteStore", s => DefaultRouteStore = s);
waitForStore("DetectedOffPlatformPremiumPerksStore", s => DetectedOffPlatformPremiumPerksStore = s);
waitForStore("DeveloperActivityShelfStore", s => DeveloperActivityShelfStore = s);
waitForStore("DeveloperExperimentStore", s => DeveloperExperimentStore = s);
waitForStore("DeveloperOptionsStore", s => DeveloperOptionsStore = s);
waitForStore("DeviceFrecencyStore", s => DeviceFrecencyStore = s);
waitForStore("DevToolsSettingsStore", s => DevToolsSettingsStore = s);
waitForStore("DevToolsDevSettingsStore", s => DevToolsDevSettingsStore = s);
waitForStore("DevToolsDesignTogglesStore", s => DevToolsDesignTogglesStore = s);
waitForStore("DimensionStore", s => DimensionStore = s);
waitForStore("DismissibleContentFrameworkStore", s => DismissibleContentFrameworkStore = s);
waitForStore("DismissibleContentShownStateStore", s => DismissibleContentShownStateStore = s);
waitForStore("DispatchApplicationLaunchSetupStore", s => DispatchApplicationLaunchSetupStore = s);
waitForStore("DispatchApplicationStore", s => DispatchApplicationStore = s);
waitForStore("DispatchManagerStore", s => DispatchManagerStore = s);
waitForStore("DraftStore", s => DraftStore = s);
waitForStore("EditMessageStore", s => EditMessageStore = s);
waitForStore("EmailSettingsStore", s => EmailSettingsStore = s);
waitForStore("EmbeddedActivitiesStore", s => EmbeddedActivitiesStore = s);
waitForStore("EmojiStore", s => EmojiStore = s);
waitForStore("EntitlementStore", s => EntitlementStore = s);
waitForStore("ExpandedGuildFolderStore", s => ExpandedGuildFolderStore = s);
waitForStore("ExperimentStore", s => ExperimentStore = s);
waitForStore("ExternalStreamingStore", s => ExternalStreamingStore = s);
waitForStore("FalsePositiveStore", s => FalsePositiveStore = s);
waitForStore("FavoritesSuggestionStore", s => FavoritesSuggestionStore = s);
waitForStore("FavoriteStore", s => FavoriteStore = s);
waitForStore("FirstPartyRichPresenceStore", s => FirstPartyRichPresenceStore = s);
waitForStore("ForumActivePostStore", s => ForumActivePostStore = s);
waitForStore("ForumPostMessagesStore", s => ForumPostMessagesStore = s);
waitForStore("ForumSearchStore", s => ForumSearchStore = s);
waitForStore("FrecencyStore", s => FrecencyStore = s);
waitForStore("FriendsStore", s => FriendsStore = s);
waitForStore("GatedChannelStore", s => GatedChannelStore = s);
waitForStore("GameConsoleStore", s => GameConsoleStore = s);
waitForStore("GameLibraryViewStore", s => GameLibraryViewStore = s);
waitForStore("GamePartyStore", s => GamePartyStore = s);
waitForStore("GameStore", s => GameStore = s);
waitForStore("GiftCodeStore", s => GiftCodeStore = s);
waitForStore("GuildAffinitiesStore", s => GuildAffinitiesStore = s);
waitForStore("GuildAvailabilityStore", s => GuildAvailabilityStore = s);
waitForStore("GuildBoostSlotStore", s => GuildBoostSlotStore = s);
waitForStore("GuildCategoryStore", s => GuildCategoryStore = s);
waitForStore("GuildChannelStore", s => GuildChannelStore = s);
waitForStore("GuildMemberCountStore", s => GuildMemberCountStore = s);
waitForStore("GuildMemberRequesterStore", s => GuildMemberRequesterStore = s);
waitForStore("GuildMemberStore", s => GuildMemberStore = s);
waitForStore("GuildNSFWAgreeStore", s => GuildNSFWAgreeStore = s);
waitForStore("GuildOnboardingHomeSettingsStore", s => GuildOnboardingHomeSettingsStore = s);
waitForStore("GuildOnboardingMemberActionStore", s => GuildOnboardingMemberActionStore = s);
waitForStore("GuildOnboardingStore", s => GuildOnboardingStore = s);
waitForStore("GuildReadStateStore", s => GuildReadStateStore = s);
waitForStore("GuildRoleStore", s => GuildRoleStore = s);
waitForStore("GuildRoleSubscriptionsStore", s => GuildRoleSubscriptionsStore = s);
waitForStore("GuildScheduledEventStore", s => GuildScheduledEventStore = s);
waitForStore("GuildSettingsStore", s => GuildSettingsStore = s);
waitForStore("GuildStickersStore", s => GuildStickersStore = s);
waitForStore("GuildStore", s => GuildStore = s);
waitForStore("GuildSubscriptionsStore", s => GuildSubscriptionsStore = s);
waitForStore("GuildTemplateStore", s => GuildTemplateStore = s);
waitForStore("GuildVerificationStore", s => GuildVerificationStore = s);
waitForStore("HookErrorStore", s => HookErrorStore = s);
waitForStore("IdleStore", s => IdleStore = s);
waitForStore("ImpersonateStore", s => ImpersonateStore = s);
waitForStore("IncomingCallStore", s => IncomingCallStore = s);
waitForStore("InstanceIdStore", s => InstanceIdStore = s);
waitForStore("InstantInviteStore", s => InstantInviteStore = s);
waitForStore("InstallationManagerStore", s => InstallationManagerStore = s);
waitForStore("IntegrationQueryStore", s => IntegrationQueryStore = s);
waitForStore("InteractionStore", s => InteractionStore = s);
waitForStore("InviteStore", s => InviteStore = s);
waitForStore("JoinedThreadsStore", s => JoinedThreadsStore = s);
waitForStore("LaunchableGameStore", s => LaunchableGameStore = s);
waitForStore("LayoutStore", s => LayoutStore = s);
waitForStore("LayerStore", s => LayerStore = s);
waitForStore("LibraryApplicationStatisticsStore", s => LibraryApplicationStatisticsStore = s);
waitForStore("LibraryApplicationStore", s => LibraryApplicationStore = s);
waitForStore("LocalActivityStore", s => LocalActivityStore = s);
waitForStore("LocaleStore", s => LocaleStore = s);
waitForStore("LoginRequiredActionStore", s => LoginRequiredActionStore = s);
waitForStore("LurkingStore", s => LurkingStore = s);
waitForStore("MaskedLinkStore", s => MaskedLinkStore = s);
waitForStore("MediaEngineStore", s => MediaEngineStore = s);
waitForStore("MessageReactionsStore", s => MessageReactionsStore = s);
waitForStore("MessageRequestStore", s => MessageRequestStore = s);
waitForStore("MessageStore", s => MessageStore = s);
waitForStore("MFAStore", s => MFAStore = s);
waitForStore("MultiAccountStore", s => MultiAccountStore = s);
waitForStore("NetworkStore", s => NetworkStore = s);
waitForStore("NewUserStore", s => NewUserStore = s);
waitForStore("NonGameStore", s => NonGameStore = s);
waitForStore("NativePermissionStore", s => NativePermissionStore = s);
waitForStore("NotificationSettingsStore", s => NotificationSettingsStore = s);
waitForStore("NotificationCenterItemsStore", s => NotificationCenterItemsStore = s);
waitForStore("NoteStore", s => NoteStore = s);
waitForStore("OverlayRTCConnectionStore", s => OverlayRTCConnectionStore = s);
waitForStore("OverridePremiumTypeStore", s => OverridePremiumTypeStore = s);
waitForStore("PaymentSourceStore", s => PaymentSourceStore = s);
waitForStore("PermissionStore", s => PermissionStore = s);
waitForStore("PermissionSpeakStore", s => PermissionSpeakStore = s);
waitForStore("PermissionVADStore", s => PermissionVADStore = s);
waitForStore("PendingReplyStore", s => PendingReplyStore = s);
waitForStore("PhoneStore", s => PhoneStore = s);
waitForStore("PictureInPictureStore", s => PictureInPictureStore = s);
waitForStore("PoggermodeSettingsStore", s => PoggermodeSettingsStore = s);
waitForStore("PoggermodeStore", s => PoggermodeStore = s);
waitForStore("PopoutWindowStore", s => PopoutWindowStore = s);
waitForStore("PremiumPaymentModalStore", s => PremiumPaymentModalStore = s);
waitForStore("PresenceStore", s => PresenceStore = s);
waitForStore("PrivateChannelSortStore", s => PrivateChannelSortStore = s);
waitForStore("PromotionsStore", s => PromotionsStore = s);
waitForStore("QuickSwitcherStore", s => QuickSwitcherStore = s);
waitForStore("QuestStore", s => QuestStore = s);
waitForStore("RawGuildEmojiStore", s => RawGuildEmojiStore = s);
waitForStore("ReadStateStore", s => ReadStateStore = s);
waitForStore("ReferencedMessageStore", s => ReferencedMessageStore = s);
waitForStore("RegionStore", s => RegionStore = s);
waitForStore("RelationshipStore", s => RelationshipStore = s);
waitForStore("RTCConnectionDesyncStore", s => RTCConnectionDesyncStore = s);
waitForStore("RTCConnectionStore", s => RTCConnectionStore = s);
waitForStore("RTCDebugStore", s => RTCDebugStore = s);
waitForStore("RTCRegionStore", s => RTCRegionStore = s);
waitForStore("RunningGameStore", s => RunningGameStore = s);
waitForStore("SaveableChannelsStore", s => SaveableChannelsStore = s);
waitForStore("SearchMessageStore", s => SearchMessageStore = s);
waitForStore("SelectivelySyncedUserSettingsStore", s => SelectivelySyncedUserSettingsStore = s);
waitForStore("SecureFramesPersistedStore", s => SecureFramesPersistedStore = s);
waitForStore("SelectedChannelStore", s => SelectedChannelStore = s);
waitForStore("SelectedGuildStore", s => SelectedGuildStore = s);
waitForStore("SelfPresenceStore", s => SelfPresenceStore = s);
waitForStore("SessionsStore", s => SessionsStore = s);
waitForStore("SlowmodeStore", s => SlowmodeStore = s);
waitForStore("SortedGuildStore", s => SortedGuildStore = s);
waitForStore("SortedVoiceStateStore", s => SortedVoiceStateStore = s);
waitForStore("SoundboardStore", s => SoundboardStore = s);
waitForStore("SoundpackStore", s => SoundpackStore = s);
waitForStore("SpamMessageRequestStore", s => SpamMessageRequestStore = s);
waitForStore("SpeakingStore", s => SpeakingStore = s);
waitForStore("SpellcheckStore", s => SpellcheckStore = s);
waitForStore("SKUStore", s => SKUStore = s);
waitForStore("SpotifyProtocolStore", s => SpotifyProtocolStore = s);
waitForStore("SpotifyStore", s => SpotifyStore = s);
waitForStore("StageChannelParticipantStore", s => StageChannelParticipantStore = s);
waitForStore("StageChannelRoleStore", s => StageChannelRoleStore = s);
waitForStore("StageChannelSelfRichPresenceStore", s => StageChannelSelfRichPresenceStore = s);
waitForStore("StageInstanceStore", s => StageInstanceStore = s);
waitForStore("StickerMessagePreviewStore", s => StickerMessagePreviewStore = s);
waitForStore("StickersPackStore", s => StickersPackStore = s);
waitForStore("StickersPersistedStore", s => StickersPersistedStore = s);
waitForStore("StickersStore", s => StickersStore = s);
waitForStore("StreamerModeStore", s => StreamerModeStore = s);
waitForStore("SubscriptionPlanStore", s => SubscriptionPlanStore = s);
waitForStore("SubscriptionRoleStore", s => SubscriptionRoleStore = s);
waitForStore("SubscriptionStore", s => SubscriptionStore = s);
waitForStore("SystemAnalyticsStore", s => SystemAnalyticsStore = s);
waitForStore("TestModeStore", s => TestModeStore = s);
waitForStore("ThemeStore", m => {
    ThemeStore = m;
    Velocity.Api.Themes.initQuickCssThemeStore(m);
});
waitForStore("ThreadMemberListStore", s => ThreadMemberListStore = s);
waitForStore("ThreadMembersStore", s => ThreadMembersStore = s);
waitForStore("ThreadMessageStore", s => ThreadMessageStore = s);
waitForStore("ThreadSummaryStore", s => ThreadSummaryStore = s);
waitForStore("TopEmojiStore", s => TopEmojiStore = s);
waitForStore("TypingStore", s => TypingStore = s);
waitForStore("UnsyncedUserSettingsStore", s => UnsyncedUserSettingsStore = s);
waitForStore("UploadAttachmentStore", s => UploadAttachmentStore = s);
waitForStore("UploadStore", s => UploadStore = s);
waitForStore("UserAffinitiesV2Store", s => UserAffinitiesV2Store = s);
waitForStore("UserGuildJoinRequestStore", s => UserGuildJoinRequestStore = s);
waitForStore("UserGuildSettingsStore", s => UserGuildSettingsStore = s);
waitForStore("UserOfferStore", s => UserOfferStore = s);
waitForStore("UserProfileStore", s => UserProfileStore = s);
waitForStore("UserRequiredActionStore", s => UserRequiredActionStore = s);
waitForStore("UserSettingsOverridesStore", s => UserSettingsOverridesStore = s);
waitForStore("UserSettingsProtoStore", s => UserSettingsProtoStore = s);
waitForStore("UserStore", s => UserStore = s);
waitForStore("VerifiedKeyStore", s => VerifiedKeyStore = s);
waitForStore("VideoBackgroundStore", s => VideoBackgroundStore = s);
waitForStore("VideoQualityModeStore", s => VideoQualityModeStore = s);
waitForStore("VideoStreamStore", s => VideoStreamStore = s);
waitForStore("VirtualCurrencyStore", s => VirtualCurrencyStore = s);
waitForStore("VoiceChannelEffectsPersistedStore", s => VoiceChannelEffectsPersistedStore = s);
waitForStore("VoiceStateStore", s => VoiceStateStore = s);
waitForStore("WindowStore", s => WindowStore = s);
waitForStore("WowMomentConfirmationStore", s => WowMomentConfirmationStore = s);
